modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"

[[mods]]
modId="invsortingmod"
version="${mod_version}"
displayName="Inventory Sorting Mod"
authors="heathcliff"
description='''An Inventory Sorting Mod made by heathcliff!'''

[[dependencies.invsortingmod]]
modId="forge"
mandatory=true
versionRange="[41,)"
ordering="NONE"
side="BOTH"

[[dependencies.invsortingmod]]
modId="minecraft"
mandatory=true
versionRange="[1.21]"
ordering="NONE"
side="BOTH"